In [12]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

In [13]:
data = load_wine()

In [6]:
data['data']

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [10]:
for key, val in data.items():
    print(key)
    print(val)

data
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
target
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
frame
None
target_names
['class_0' 'class_1' 'class_2']
DESCR
.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three clas

In [14]:
X_train, x_test, Y_train, y_test = train_test_split(data['data'], data['target'])

In [29]:
reggressor = LinearRegression().fit(X_train, Y_train)

In [30]:
prediction = reggressor.predict(x_test)

In [31]:
np.array([prediction, y_test])

array([[ 0.46008393,  1.30363565,  1.0966678 ,  1.76638596, -0.0086934 ,
         0.90028035,  1.73185716,  1.29900109,  0.23158912,  0.16905841,
         0.80836045,  0.93644713,  0.20360086,  1.88589404,  2.25379558,
         0.62307091,  1.69040608,  1.28854995,  1.53649959,  0.02096518,
         2.07946771,  0.81255295,  0.92896601,  2.11078958,  1.09625504,
         1.88780875,  0.05100537,  1.03540275, -0.2261311 ,  1.36636966,
         2.06045423,  0.67144157, -0.12939242,  0.09193333,  1.9238671 ,
         1.66511426,  2.00064735, -0.2769989 ,  1.33856971,  1.87408092,
         0.96855134,  1.25551939,  1.19604134,  1.30029944,  1.23332943],
       [ 0.        ,  1.        ,  1.        ,  1.        ,  0.        ,
         1.        ,  2.        ,  1.        ,  0.        ,  0.        ,
         1.        ,  1.        ,  0.        ,  2.        ,  2.        ,
         1.        ,  2.        ,  1.        ,  1.        ,  0.        ,
         2.        ,  1.        ,  1.        ,  2.

In [24]:
y_test

array([0, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 0, 2, 2, 1, 2, 1, 1, 0, 2, 1,
       1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 1, 0, 2, 1, 2, 0, 1, 2, 1, 1, 1, 1,
       1])

In [1]:
!pip install tensorflow

^C
