In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

X = np.array([
    [1, 1],
    [1, 2],
    [2, 2],
    [2, 3]
])

y = np.array([0.2, 2, 1, 2]) + 11
regressor = LinearRegression().fit(X, y)

print(regressor.predict(np.array([[3, 5]])))

[15.]


In [2]:
regressor.coef_

array([-1. ,  1.4])

In [3]:
regressor.predict(np.array([[1, 2]]))

array([12.8])

In [4]:
y

array([11.2, 13. , 12. , 13. ])

In [5]:
 def twoSum(nums, target):
    d = {}
    for i, n in enumerate(nums):
        m = target - n
        if m in d:
            return [d[m], i]
        else:
            d[n] = i

In [6]:
twoSum([1, 2, 3, 5, 6, 7, 10], 8)

[2, 3]

In [7]:


def target_sum(num_list, targ):
    buffer_dict = {}
    for i in num_list:
        tg_numb1 = targ - i
        if tg_numb1 in buffer_dict:
            return [buffer_dict[tg_numb1], tg_numb1]
        else:
            buffer_dict[i] = tg_numb1



In [11]:
data = [1, 2, 3, 5, 6, 7, 10]
data.index(5)
# target = 8
# target_sum(data, target)

3