In [1]:
import tensorflow as tf

In [4]:
x = tf.constant([[1],[2]])
y = tf.constant([[2, 3]])

In [8]:
x

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [2]])>

In [9]:
y

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]])>

In [14]:
tf.Variable(tf.random.normal([20, 2]))
def f(x):
    return 1 / x ** 2

In [17]:
x0 = tf.Variable(2.0)
with tf.GradientTape() as tape:
    y = f(x0)
    dydx = tape.gradient(y, x0)
    print(dydx)

tf.Tensor(-0.25, shape=(), dtype=float32)


In [19]:
class DenseLayer(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name="w"
        )
        self.b = tf.Variable(tf.zeros([out_features]), name="b")

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)


In [20]:
class NN(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.layer_1 = DenseLayer(in_features=3, out_features=3)
        self.layer_2 = DenseLayer(in_features=3, out_features=1)

    def __call__(self, x):
        x = self.layer_1(x)
        return self.layer_2(x)


nn = NN(name="neural_network")
print("Results:", nn(tf.constant([[2.0, 2.0, 2.0]])))

Results: tf.Tensor([[3.70475]], shape=(1, 1), dtype=float32)


In [24]:
tf.Variable(tf.zeros([2, 5]))

<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.33333334, 0.33333334, 0.33333334]], dtype=float32)>