In [6]:
import numpy as np

In [8]:
np.array

<function numpy.array>

In [13]:
np.array?

In [17]:
values = np.array([1, 2, 3, 4, 5])

In [15]:
a

array([1, 2, 3, 4, 5])

In [16]:
print(a)

[1 2 3 4 5]


In [18]:
for val in values:
    print(val)

1
2
3
4
5


In [20]:
matrix = np.array([ [1, 2], [3, 4] ])

In [21]:
matrix

array([[1, 2],
       [3, 4]])

In [22]:
print(matrix)

[[1 2]
 [3 4]]


In [23]:
matrix * 3

array([[ 3,  6],
       [ 9, 12]])

In [24]:
matrix + 3

array([[4, 5],
       [6, 7]])

In [26]:
a = np.array([[1,2], [3,4]])

In [28]:
b = np.array([[10,20],[30,40]])

In [29]:
a

array([[1, 2],
       [3, 4]])

In [30]:
b

array([[10, 20],
       [30, 40]])

In [32]:
np.matmul?

In [33]:
np.matmul(a, b)

array([[ 70, 100],
       [150, 220]])

In [39]:
np.prod(a)


24

In [40]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [42]:
a = np.array([np.pi, np.pi/3])

In [43]:
np.cos(a)

array([-1. ,  0.5])

In [44]:
a

array([3.14159265, 1.04719755])

In [51]:
a = np.array([0.1, 0.4, 0.3, 0.4])

In [47]:
a.sum()

1.0

In [48]:
max(a)

0.4

In [52]:
a.argmax()

1

In [50]:
a.max()

0.4

In [53]:
a.sort()

In [54]:
a

array([0.1, 0.3, 0.4, 0.4])

In [57]:
a.ndim

1

In [58]:
a

array([0.1, 0.3, 0.4, 0.4])

In [59]:
b

array([[10, 20],
       [30, 40]])

In [60]:
b.ndim

2

In [61]:
b.shape

(2, 2)

In [62]:
b.size

4

In [63]:
a = np.array([[0.1, 0.3, 0.4, 0.4],[0.1, 0.3, 0.4, 0.4]])

In [64]:
a

array([[0.1, 0.3, 0.4, 0.4],
       [0.1, 0.3, 0.4, 0.4]])

In [66]:
a.T

array([[0.1, 0.1],
       [0.3, 0.3],
       [0.4, 0.4],
       [0.4, 0.4]])

In [68]:
a_trans = np.transpose(a)

In [69]:
a_trans

array([[0.1, 0.1],
       [0.3, 0.3],
       [0.4, 0.4],
       [0.4, 0.4]])

In [70]:
a.reshape(4, 2)

array([[0.1, 0.3],
       [0.4, 0.4],
       [0.1, 0.3],
       [0.4, 0.4]])

In [71]:
a.shape

(2, 4)

In [110]:
a = np.array([10, -258], dtype='int8')

In [74]:
a.itemsize

1

In [75]:
a.data

In [111]:
a.data.hex()

'0afe'

In [77]:
a.data.tolist()

[1, 2]

In [112]:
a = np.array([123.34], dtype='float16')


In [113]:
a.data.hex()

'b557'

In [114]:
np.matrix?


In [115]:
a = np.matrix([[1,2],[3,4]])

In [117]:
a

matrix([[1, 2],
        [3, 4]])

In [118]:
b = np.matrix([[3,4],[5,6]])

In [119]:
b

matrix([[3, 4],
        [5, 6]])

In [120]:
a * b

matrix([[13, 16],
        [29, 36]])

In [122]:
a = np.array([1,2,3,4])

In [123]:
mask = np.array([0,1,0,0])

In [124]:
np.matmul(a,mask)

2

In [125]:
a * mask

array([0, 2, 0, 0])

In [126]:
b = np.array([2, 3, 1, 0])

In [127]:
a.dot(b)

11

In [128]:
(a * b).sum()

11

In [129]:
a.dot(b)

11

In [130]:
a.dot?