In [1]:
import numpy as np

In [2]:
a = np.array([[3, -4, 1], [-1, -5, 3], [1, -1, 1]])

In [3]:
np.linalg.det(a)

-15.999999999999998

In [4]:
b = np.array([[3, -1, 1], [1, -5, 3], [1, -1, 1]])

In [5]:
np.linalg.det(b)

-4.000000000000002

In [6]:
c = np.array([[2, -4, 1], [3, -1, 1], [1, -1, 1]])

In [7]:
np.linalg.det(c)

6.000000000000003

In [8]:
d = np.array([[2, -4, 1], [3, -1, 1], [1, -1, 1]])

In [9]:
a

array([[ 3, -4,  1],
       [-1, -5,  3],
       [ 1, -1,  1]])

In [10]:
p = np.array([[3, -1, 1]]).reshape(3, 1)

In [11]:
p

array([[ 3],
       [-1],
       [ 1]])

In [12]:
np.linalg.solve(a, p)

array([[ 1.],
       [-0.],
       [ 0.]])

In [15]:
a = np.array([[5, -3, 2, 4], [4, -2, 3, 7], [3, -6, -1, -5], [7, -3, 7, 17]])

In [19]:
a_inv = np.linalg.inv(a)

In [20]:
b = np.array([[3, 1, 9, 0]]).reshape(4, 1)

In [21]:
b

array([[3],
       [1],
       [9],
       [0]])

In [23]:
np.linalg.solve(a, b)

array([[-1.26882631e-16],
       [-1.40000000e+00],
       [-6.00000000e-01],
       [ 0.00000000e+00]])

In [24]:
a_inv.dot(b)

array([[-1.44285714],
       [-2.3325    ],
       [-0.93625   ],
       [ 0.40625   ]])